server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    location / {
        try_files  / /index.html;
    }
    location /api {
        proxy_pass http://frappe:8000/api;
        # ... (rest of proxy config)
    }
    location /files {
        proxy_pass http://frappe:8000/files;
        # ... (rest of proxy config)
    }
}
